# Problem 2: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# -- Solution 1 --

# Populate array of natural numbers under 1000.
num_arr = (1..999).to_a;

# Selecting all multiples of 3 and 5
num_multiple = num_arr.select { |x| x%3==0 || x%5==0 }

# Sum of those multiples
puts num_sum = num_multiple.reduce(:+)
