=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

# ---METHOD 1:

# Declaring variables
term_1 = 1
term_2 = 2
terms = 0
terms_array = [1, 2]

# Iteration
until terms >= 4000000 do
	terms = term_1 + term_2
	terms_array.push(terms)
	term_1 = term_2
	term_2 = terms
end

# a.pop removes the last element in an array
terms_array.pop

# Selecting even terms in an array
even_terms = terms_array.select { |i| i%2 == 0 }

# Displays the sum of even terms
puts even_terms.reduce(:+)
